apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-sa
  namespace: propdevelopment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: security-sa
  namespace: propdevelopment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher-sa
  namespace: propdevelopment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smarthome-operator-sa
  namespace: smarthome
